accounts/urls.py
from django.urls import path
from .views import *

app_name='accounts'

urlpatterns = [
    path('register/', register_user, name="register" ),
    path('login/', login_user, name="login" ),
    path('logout/', logout_user, name="logout" ),
    path('profile/', profile_page, name="profile" ),
    path('user_edit/', user_edit, name="user_edit" ),
    path('profile_edit/', profile_edit, name="profile_edit" ),
    path('edit-account/', edit_password, name="edit-account" ),
    path('call_us/', call_us, name="call" ),
    path('reset/<uidb64>/<token>/', Custom_PasswordResetConfirm.as_view(template_name="accounts/password_reset_confirm.html"), name='password_reset_confirm'),
    path('password_reset/', Custom_PasswordResetView.as_view(template_name='accounts/password_reset.html'), name='password_reset'),
    path('password_reset/done/', Custom_PasswordResetDone.as_view(template_name='accounts/password_reset_done.html'), name='password_reset_done'),
    path('reset/done/', Custom_PasswordResetCompelte.as_view(), name='password_reset_complete'),    

]

products/urls.py
from django.urls import path
from . import views

app_name='products'

urlpatterns = [
    path('category/<str:name>', views.show_products, name = "show-products"),
    path('<int:pk>/', views.detail_product, name = "detail-product"),
    path('search/', views.result_search, name = "search"),
    path('comment/<int:pk>/', views.send_comment, name = "send-comment"),
    path('reply_comment/<int:pk>/', views.send_reply, name = "send-reply"),
    path('liked/<int:pk>/', views.add_likes, name = "add-likes"),
    path('add_order', views.add_order, name = "add-order"),
    path('update_order', views.update_order, name = "update-order"),
    path('show_cart', views.show_cart, name = "show-cart"),
    path('liked_list/', views.show_likes, name = "liked-list"),
    path('about_us/', views.about_us, name = "about-us"),
    path('delete_liked/<int:pk>/', views.delete_liked, name = "delete_liked"),
    path('delete_orderItem/<int:pk>/', views.delete_orderItem, name = "delete_order_item"),
    path('confirm_order/', views.confirm_order, name = "confirm-order"),
    path('select_delivery/', views.select_delivery, name = "select-delivery"),


    
     
]

sazCitysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
import accounts

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('product/', include('products.urls')),
    path('', accounts.views.main_page, name="main-page"),

]
handler404 = 'accounts.views.error_404'

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

accounts/models.py
from tkinter import N
from django.db import models
from django.contrib.auth.models import AbstractUser


class Custom_user(AbstractUser):
    first_name = None
    last_name = None
    email = models.EmailField(blank = False, unique = True)
    rate = models.IntegerField(default=0)

    class Meta:
        verbose_name_plural = "کاربران"


class User_info(models.Model):
    user = models.OneToOneField(Custom_user, on_delete = models.CASCADE)
    first_name = models.CharField(max_length = 30)
    last_name = models.CharField(max_length = 30)
    address_1 = models.CharField(max_length = 128)
    address_2 = models.CharField(max_length = 128, blank = True)
    state = models.CharField(max_length = 64)
    city = models.CharField(max_length = 64)
    post_code = models.CharField(max_length = 10, null=False) 
    phone_number = models.CharField( max_length = 11)  

    def __str__(self):
        return f'info of {self.user}'

    class Meta:
        verbose_name_plural = "اطلاعات کاربران"


class Slider(models.Model):
    caption = models.CharField(max_length = 30)
    pic = models.ImageField(upload_to = 'slider_pics')
    state = models.CharField(max_length = 7)
    data_slide_to = models.IntegerField()

    class Meta:
        verbose_name_plural = "اسلایدر"

accounts/forms.py
from .models import Custom_user, User_info
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, PasswordChangeForm
from django import forms
from django.utils.translation import  gettext_lazy as _


class Custom_userCreationForm(UserCreationForm):
    error_messages = {
        'password_mismatch': _("دو رمز عبور یکسان نیستند"),
    }
    username = forms.CharField(label=_("نام کاربری"), widget= forms.TextInput (attrs={'placeholder':'نام کاربری'}), help_text=_('Required. 30 characters or fewer. Letters, digits and ''@/./+/-/_ only.'))
    email = forms.EmailField(label=_("ایمیل"), widget= forms.TextInput (attrs={'placeholder':'ایمیل'}))
    password1 = forms.CharField(label=_("رمز عبور"), widget=forms.PasswordInput(attrs={'placeholder':'رمز عبور'}))
    password2 = forms.CharField(label=_("تکرار رمز عبور"), widget=forms.PasswordInput(attrs={'placeholder':'تکرار رمز عبور'}), help_text=_("رمز عبور قسمت بالا را تکرار کنید."))
    class Meta:
        model = Custom_user
        fields = ['username','email']
        
 
class Custom_authentication_form(AuthenticationForm):
    username = forms.CharField(label=_("نام کاربری"), max_length=254)
    password = forms.CharField(label=_("رمز عبور"), widget=forms.PasswordInput)


class Custom_PasswordChangeForm(PasswordChangeForm):

    old_password = forms.CharField(label=_("رمز عبور قبلی"), widget=forms.PasswordInput)

    new_password1 = forms.CharField(label=_("رمز عبور جدید"), widget=forms.PasswordInput)

    new_password2 = forms.CharField(label=_("تکرار رمز عبور جدید"), widget=forms.PasswordInput)
   

class Profile_form(ModelForm):
    post_code = forms.CharField(max_length=10, min_length=10, label=_("کد پستی"))
    phone_number = forms.CharField(max_length=11, min_length=11, label=_("شماره همراه"))
    class Meta:
        model = User_info
        fields = ['first_name', 'last_name', 'address_1', 'address_2', 'state', 'city', 'post_code', 'phone_number']
        labels = {
            "first_name": ("نام"),
            "last_name" : ("نام خانوادگی"),
            "address_1": ("آدرس"),
            "address_2": ("آدرس"),
            "state": ("استان"),
            "city": ("شهر"),
        }
    def clean(self):
        # data from the form is fetched using super function
        super(Profile_form, self).clean()
         
        # extract the username and text field from the data
        first_name = self.cleaned_data.get('first_name')
        last_name = self.cleaned_data.get('last_name')
        state = self.cleaned_data.get('state')
        city = self.cleaned_data.get('city')
 
        is_digit_in_first_name = any(char.isdigit() for char in first_name)
        is_digit_in_last_name = any(char.isdigit() for char in last_name)
        is_digit_in_state = any(char.isdigit() for char in state)
        is_digit_in_city = any(char.isdigit() for char in city)
        if is_digit_in_first_name:  
             self._errors['first_name'] = self.error_class([
                'Minimum 5 characters required'])

        if is_digit_in_last_name:  
             self._errors['last_name'] = self.error_class([
                'Minimum 5 characters required'])

        if is_digit_in_state:  
             self._errors['state'] = self.error_class([
                'Minimum 5 characters required'])

        if is_digit_in_city:  
             self._errors['city'] = self.error_class([
                'Minimum 5 characters required'])

        return self.cleaned_data


class Update_account(ModelForm):
     class Meta:
        model = Custom_user
        fields = ['email', 'username',]
        labels = {
            "email": ("ایمیل"),
            "username" : ("نام کاربری"),
         }


class Call_form(forms.Form):
    subject = forms.CharField(label=_("عنوان"), widget= forms.TextInput (attrs={'placeholder':'عنوان'}), max_length=25)
    message= forms.CharField(label=_("پیام"), widget=forms.Textarea(attrs={'placeholder':'متن پیام'}))

accounts/views.py
from urllib import request
from django.shortcuts import redirect, render
from .forms import *
from products.models import Product
from django.contrib.auth import login, logout
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy
from django.conf import settings
from django.core.mail import send_mail
from django.contrib import messages
from django.http import  Http404
from django.core.paginator import Paginator
from django.contrib.auth.mixins import UserPassesTestMixin
from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView


def main_page(request):
    products = Product.objects.all().order_by('-id')
    filter = " "
    
    if 'next' in request.GET:
         messages.error(request, 'ابتدا وارد حساب کاربری خود شوید.')

    if 'filter' in request.GET:
        filter_id = request.GET['filter']
        if filter_id == '1' :
            products = products.order_by('-id')
            filter = "جدید"

        elif filter_id == '2':
            products = sorted(products, key= lambda product : product.avg_rate(), reverse=True)
            filter = "محبوب"

        elif filter_id == '3':
            products = products.order_by('-sold')
            filter = "پر فروش"

        else:
            raise Http404()


    paginator = Paginator(products, 12)
    page_number = request.GET.get('page')
    products_in_page = paginator.get_page(page_number)
    context ={
        'products_in_page' : products_in_page,
        'filter' : filter
    }
    return render(request, 'accounts/main.html', context)


def register_user(request):
    if request.method == "POST":
        form = Custom_userCreationForm(request.POST)
        if form.is_valid():
            form.save()
            #login(request, user)
            messages.success(request, 'ثبت نام با موفقیت انجام شد ')
        else:
            messages.warning(request, 'اطلاعات نادرست است')

    return redirect("main-page")
   

def login_user(request):
    if request.method == "POST":
        form = Custom_authentication_form(data = request.POST)
        if form.is_valid():
            user=form.get_user()
            login(request, user)
            messages.success(request, 'با موفقیت وارد حساب کاربری خود شدید')       
        else:
            messages.warning(request, 'اطلاعات نامعتبر است')

    return redirect("main-page")
    

@login_required(login_url='/')
def logout_user(request):
    if request.method == "POST":
        logout(request)
        messages.error(request, 'با موفقیت از حساب کاربری خود خارج شدید')

    return redirect('/')


@login_required(login_url='/')  
def profile_page(request):
    user = request.user
    user_form = Update_account(instance = user)      
    profile_form = Profile_form(instance = user.user_info)

    context={
        'u_form' : user_form,
        'p_form' : profile_form
    }
    return render(request, 'accounts/profile.html', context) 


# edit main info of user(custom_user table)
@login_required(login_url='/')  
def user_edit(request):
    if request.method == "POST":
        user_form = Update_account(request.POST, instance = request.user)

        if user_form.is_valid():
            user_form.save()
            messages.success(request, 'اطلاعات با موفقیت بروزرسانی شد')
        else:
            messages.error(request, 'اطلاعات نامعتبر است!')

    return redirect('accounts:profile')
            

# edit user_info table
@login_required(login_url='/')  
def profile_edit(request):
    if request.method == "POST":
        profile_form = Profile_form(request.POST, instance = request.user.user_info)
     
        if profile_form.is_valid():
            profile_form.save()
            messages.success(request, 'اطلاعات با موفقیت بروزرسانی شد')
        else:
             messages.error(request, 'اطلاعات نامعتبر است!')

    return redirect('accounts:profile')

                 
@login_required(login_url = '/')
def edit_password(request):
    if request.method == "POST":
        password_form = Custom_PasswordChangeForm(request.user, request.POST)
      
        if password_form.is_valid():
            password_form.save()
            update_session_auth_hash(request, request.user) 
            messages.success(request, 'رمز عبور شما با موفقیت تغییر یافت')
        else:
           messages.error(request, 'رمز عبور وارد شده نامعتبر است.')
    else:
        password_form = Custom_PasswordChangeForm(request.user)

    context={
            'password_form' : password_form
        }

    return render(request, 'accounts/edit_account.html', context)


class Custom_PasswordResetView(UserPassesTestMixin, PasswordResetView):
    template_name = 'accounts/password_reset.html'
    email_template_name = "accounts/password_reset_email.html"
    success_url = reverse_lazy("accounts:password_reset_done")

    def test_func(self):
        return self.request.user.is_anonymous


class Custom_PasswordResetDone(UserPassesTestMixin, PasswordResetDoneView):
    template_name = 'accounts/password_reset_done.html'

    def test_func(self):
        return self.request.user.is_anonymous


class Custom_PasswordResetConfirm(UserPassesTestMixin, PasswordResetConfirmView):
    template_name = 'accounts/password_reset_confirm.html'
    success_url = reverse_lazy("accounts:password_reset_complete")

    def test_func(self):
        print(self.request.session.get('_password_reset_token'))
        return self.request.user.is_anonymous


class Custom_PasswordResetCompelte(UserPassesTestMixin, PasswordResetCompleteView):
    template_name = 'accounts/password_reset_complete.html'

    def test_func(self):
        return self.request.user.is_anonymous


def call_us(request):
    if request.method=='POST':
        call_form = Call_form(request.POST)

        if call_form.is_valid():
            subject = call_form.cleaned_data['subject']
            msg = call_form.cleaned_data['message']
            if not request.user.is_anonymous:
                new_line ='\n'
                msg += f"{new_line} this email is sent from {request.user.email}"
            email_from = settings.EMAIL_HOST_USER
            recipient_list = [settings.EMAIL_HOST_USER, ]
            send_mail( subject, msg, email_from, recipient_list )
            messages.success(request, 'پیام با موفقیت ارسال شد')
        else:
            messages.warning(request, 'اطلاعات نا معتبر است ')
        return redirect("accounts:call")

    call_form = Call_form()
    context ={
        'call_form' : call_form

    }
    return render(request, 'accounts/call.html', context)


#custom error 404 page
def error_404(request, exception):
    return render(request, 'accounts/404.html')

accounts/templates/accounts/call.html
{% extends 'base.html' %}
{% load static %}

{% block headers %}
{% endblock headers %}


{% block content %}

    <div class="messages" >
        {% if messages %}
        <ul >
            {% for message in messages %}
            <li>
                <div class="alert alert-{{ message.tags }}" role="alert">{{ message }}</div>
            </li>
            {% endfor %}
        </ul>
    {% endif %}
    </div>

    <div class="row" >
        <div class="col-2 col-md-2"></div>
        <div class="col-8 col-md-8 shadow-lg p-3 mb-5 bg-white rounded" id="call_us">
            <h5> نظرات خود را با ما در میان بگذارید</h5>
            <hr>
            <form action="" method="POST">
                {% csrf_token %}
            
                <div>
                    {{call_form.subject}}
                </div>

                <div>
                    {{call_form.message}}
                </div>
                <div class="button_wrapper">
                    <button type="submit" class="btn btn-danger">ارسال پیام</button>
                </div>
                
            </form> 
        </div>
        
        <div class="col-2 col-md-2"></div>
    </div>

{% endblock content %}

accounts/templates/accounts/edit_account.html
{% extends 'base.html' %}
{% load static %}
{% block extrahead %}

    <link rel="stylesheet" type="text/css" href="{% static 'products/css/style.css' %}">

{% endblock %}

{% block headers %}
{% endblock headers %}


{% block content %}

    <div class="messages">
        {% if messages %}
        <ul >
            {% for message in messages %}
            <li>
                <div class="alert alert-{{ message.tags }}" role="alert">{{ message }}</div>
            </li>
            {% endfor %}
        </ul>
    {% endif %}
    </div>
 
    <div class="row profile_wrapper">
        <div class="col-2"></div>
        <div class="col-8">
            <h3>تغییر رمز عبور</h3>
            <hr>
            <form action="" method="POST">
                {% csrf_token %}
                {% for field in password_form %}
                    <div class="form_field row">
                        <div class="label col-12 ">  {{field.label}}  : </div>
                        <div class="form_content col-12 ">  {{field}}</div>
                    </div>
                {% endfor %}
                <br>
                <div>
                    {% if password_form.errors %}
                        {% for field in password_form %}
                            {% for error in field.errors %}
                                <div class="alert alert-danger">
                                    <strong>{{ error|escape }}</strong>
                                </div>
                            {% endfor %}
                        {% endfor %}
                     {% endif %}
                </div>
             
                <div class="button_wrapper"> <button class="btn btn-sm btn-danger" type="submit" >ذخیره تغییرات </button></div> 
            </form>
        </div>
        <div class="col-2"></div>
    </div>

        
{% endblock content %}

accounts/templates/accounts/logout.html
{% extends 'base.html' %}


{% block content %}

    <form action="" method="POST">

        {% csrf_token %}
        <button type="submit" >logout </button>
        <a href="{% url 'accounts:login' %}" type="button" >cancel </a>

    </form>
    


{% endblock content %}

accounts/templates/accounts/main.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}
{% block extrahead %}

    <link rel="stylesheet" type="text/css" href="{% static 'products/css/style.css' %}">

{% endblock %}

{% block banner %}{% endblock banner%}
{% block content %}

  <div class="messages">
    {% if messages %}
    <ul >
        {% for message in messages %}
        <li>
            <div class="alert alert-{{ message.tags }}" role="alert">{{ message }}</div>
        </li>
        {% endfor %}
    </ul>
  {% endif %}
  </div>

   {% if filter %}
    <div class="filter">
        <form  method="GET">
          <label> مرتب سازی بر اساس :</label>
          <select name='filter' onchange='if(this.value != 0) { this.form.submit(); }'>
              <option value='0'>{{filter}}</option>
              <option value='1'>جدید</option>
              <option value='2'>محبوب</option>
              <option value='3'>پر فروش</option>
          </select>
        </form>
    </div>
  {% endif %}
        
  {% if products_in_page %}

    <div class="row wrapper">
      {% for product in products_in_page %}

        <div class="col-12 col-sm-6 col-md-6 col-lg-3 card">
          <a href="{% url 'products:detail-product' product.id %}">
            <img class="card-img-top" src="{{product.pic.url}}" alt="Card image cap">

            <div class="card-body">

              <h5 class="card-title">{{product.category_item}} : {{product.product_name}}</h5>
              <h5 class="card-rate">{{product.avg_rate}} <span class="fa fa-star" style=" color: orange;"></span></h5> 
              
              {% if product.total_number == 0 %}
                  <h6 class="card-text text-danger">{{product.existance}}</h6>
              {% else %}
                  <h6 class="card-text text-danger">{{product.total_number}}  عدد در انبار  </h6>
              {% endif %}
              {% if product.discount %}
                  <h6 class="card-price"><sup class=" text-danger font-weight-bold"> %{{product.discount.percent}} </sup><span class="line-through">{{product.price|intcomma}} ریال</span></h6>
                  <h6 class="card-price text-success">{{product.get_discount|intcomma}} ریال</h6>  
              {% else %}
                  <h6 class="card-price">{{product.price|intcomma}} ریال</h6> 
              {% endif %}
              
            
            </div>
            </a>
        </div>
      
      {% endfor %}
    </div>
        
    <div class="pagination-wrapper">
      <ul class="pagination">
        {% if products_in_page.has_previous %}
          <li class="page-item">
            <a class="page-link" href="?page={{ products_in_page.previous_page_number }}" tabindex="-1">قبل</a>
          </li>
        {% else %}
          <li class="page-item disabled">
            <a class="page-link" href="#" tabindex="-1">قبل</a>
        </li>
        {% endif %}

        {% for i in products_in_page.paginator.page_range %}
          {% if products_in_page.number == i %}
            <li class="page-item active">
              <a class="page-link" href="#">{{ i }} <span class="sr-only">(current)</span></a>
            </li>
          {% else %}
            <li class="page-item"><a class="page-link"  href="?page={{ i }}">{{ i }}</a></li>
          {% endif %}
        {% endfor %}

        {% if products_in_page.has_next %}
          <li class="page-item">
            <a class="page-link" href="?page={{ products_in_page.next_page_number }}" tabindex="-1">بعد</a>
          </li>
        {% else %}
          <li class="page-item disabled">
            <a class="page-link" href="#" tabindex="-1">بعد</a>
        </li>
        {% endif %}
      </ul>
    </div> 
    
  {% endif %}

{% endblock content %}

accounts/templates/accounts/password_reset.html
{% extends 'base.html' %}
{% load static %}

{% block headers %}
{% endblock headers %}

{% block navbar %}
{% endblock navbar %}

{% block content %}

        

	<!--Reset Password-->
	<div class="container p-5 reset_form">
  	 	<h4 class="font-weight-bold mt-3">بازیابی رمز عبور </h4>
		<hr>
		<p>  برای بازیابی رمز، ایمیل خود را وارد نمایید.</p>
        <form method="POST">
            {% csrf_token %}
                            
            <div class="row">
                <div class="col-12 ">
                    <label>ایمیل :</label>
                    {{ form.email }}  
                </div>
                <hr>
                <div class="button_wrapper col-12 "> <button  class="btn btn-danger" type="submit" >ارسال  </button></div> 
           </div>
        </form>

        <div>
            {% if form.errors %}
                {% for field in form %}
                    {% for error in field.errors %}
                        <div class="alert alert-danger">
                            <strong>{{ error|escape }}</strong>
                        </div>
                    {% endfor %}
                {% endfor %}
             {% endif %}
        </div>
  	</div> 

{% endblock content%}

accounts/templates/accounts/password_reset_complete.html
{% extends 'base.html' %}
{% load static %}

{% block headers %}
{% endblock headers %}

{% block navbar %}
{% endblock navbar %}

{% block content %}

<div class="container p-4">
    <h4 class="font-weight-bold mt-3">بازیابی رمز عبور با موفقیت انجام شد</h4>
    <hr>
    <p>می توانید وارد حساب کاربری خود شوید</p>                 
    <a href="{% url 'main-page'%}" class="btn btn-danger">صفحه اصلی</a>
</div>

{% endblock content%}

accounts/templates/accounts/password_reset_confirm.html
{% extends 'base.html' %}
{% load static %}

{% block headers %}
{% endblock headers %}

{% block navbar %}
{% endblock navbar %}


{% block content %}
<div class="container p-5 reset_form">
    <h4 class="font-weight-bold mt-3">فرم بازیابی رمز عبور</h4>
    <hr>
    <p>لطفا رمز عبور جدید را وارد نمایید</p>
    <form method="POST">
        {% csrf_token %}
            <div style="display: flex;justify-content: center;" class="row">
                <label class="col-12 "> رمز عبور جدید:</label>
                {{ form.new_password1}}  
            </div>
             <div style="display: flex;justify-content: center;" class="row">
                <label class="col-12 " >تکرار رمز عبور جدید :</label> 
                {{ form.new_password2}}
             </div>  
             <div class=" button_wrapper"> <button  class="btn btn-danger" type="submit" >ارسال  </button></div>                  
    </form>

    <div>
        {% if form.errors %}
            {% for field in form %}
                {% for error in field.errors %}
                    <div class="alert alert-danger">
                        <strong>{{ error|escape }}</strong>
                    </div>
                {% endfor %}
            {% endfor %}
         {% endif %}
    </div>
</div>
{% endblock content%}

accounts/templates/accounts/password_reset_done.html
{% extends 'base.html' %}
{% load static %}

{% block headers %}
{% endblock headers %}


{% block content %}
<div class="container p-5">
    <h5 class="font-weight-bold mt-3">ایمیل بازیابی برای شما ارسال شد.</h5>
      <hr>
      <p>اگر ایمیل وارد شده معتبر باشد، به زودی آن را دریافت خواهید کرد</p>
</div>
{% endblock content%}

accounts/templates/accounts/password_reset_email.html
{% autoescape off %}
سلام

ما درخواستی مبنی بر بازیابی رمز عبور اکانت مرتبط با ایمیل شما دریافت کرده ایم. برای بازیابی رمز روی لینک زیر کلیک نمایید

{{ protocol }}://{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}

این لینک تنها یک بار قابل استفاده است. برای بازبابی مجدد به این صفحه مراجعه کنید 
{{ protocol }}://{{domain}}
و درخواست دیگری بدهید

تیم شهر ساز

{% endautoescape %}

accounts/templates/accounts/profile.html
{% extends 'base.html' %}

{% block headers %}
{% endblock headers%}

{% block content %}

    <div class="messages" >
        {% if messages %}
        <ul >
            {% for message in messages %}
            <li>
                <div class="alert alert-{{ message.tags }}" role="alert">{{ message }}</div>
            </li>
            {% endfor %}
        </ul>
       {% endif %}
    </div>

    <div class="row profile_wrapper">
        <div class="col-2"></div>
        <div class="col-8">
            <h5>اطلاعات اصلی</h5>
            <hr>
            <form action="{% url 'accounts:user_edit' %}" method="POST">
                {% csrf_token %}
                {% for field in u_form %}
                    <div class="form_field row">
                        <div class="label col-12 col-md-5">  {{field.label}} :</div>
                        <div class="form_content col-12 col-md-6">  {{field}}</div>
                    </div>
                {% endfor %}
                <br>
                <div class="button_wrapper"> <button class="btn btn-danger" type="submit" >ذخیره تغییرات </button></div> 
            </form>
            <br>
            <h5>مشخصات تکمیلی</h5>
            <hr>
            <form action="{% url 'accounts:profile_edit' %}" method="POST">
                {% csrf_token %}

                {% for field in p_form %}
                    <div class="form_field row">
                        <div class="label col-12 col-md-5">  {{field.label}} :</div>
                        <div class="form_content col-12 col-md-6">  {{field}}</div>
                    </div>
                {% endfor %}
                <br>
                 <div class="button_wrapper"> <button class="btn btn-danger" type="submit" >ذخیره تغییرات </button></div> 
            </form>
            <hr>
        </div>
        <div class="col-2"></div>
    </div>
    
{% endblock content %}