accounts/urls.py
from django.urls import path
from .views import *

app_name='accounts'

urlpatterns = [
    path('register/', register_user, name="register" ),
    path('login/', login_user, name="login" ),
    path('logout/', logout_user, name="logout" ),
    path('profile/', profile_page, name="profile" ),
    path('user_edit/', user_edit, name="user_edit" ),
    path('profile_edit/', profile_edit, name="profile_edit" ),
    path('edit-account/', edit_password, name="edit-account" ),
    path('call_us/', call_us, name="call" ),
    path('reset/<uidb64>/<token>/', Custom_PasswordResetConfirm.as_view(template_name="accounts/password_reset_confirm.html"), name='password_reset_confirm'),
    path('password_reset/', Custom_PasswordResetView.as_view(template_name='accounts/password_reset.html'), name='password_reset'),
    path('password_reset/done/', Custom_PasswordResetDone.as_view(template_name='accounts/password_reset_done.html'), name='password_reset_done'),
    path('reset/done/', Custom_PasswordResetCompelte.as_view(), name='password_reset_complete'),    

]

products/urls.py
from django.urls import path
from . import views

app_name='products'

urlpatterns = [
    path('category/<str:name>', views.show_products, name = "show-products"),
    path('<int:pk>/', views.detail_product, name = "detail-product"),
    path('search/', views.result_search, name = "search"),
    path('comment/<int:pk>/', views.send_comment, name = "send-comment"),
    path('reply_comment/<int:pk>/', views.send_reply, name = "send-reply"),
    path('liked/<int:pk>/', views.add_likes, name = "add-likes"),
    path('add_order', views.add_order, name = "add-order"),
    path('update_order', views.update_order, name = "update-order"),
    path('show_cart', views.show_cart, name = "show-cart"),
    path('liked_list/', views.show_likes, name = "liked-list"),
    path('about_us/', views.about_us, name = "about-us"),
    path('delete_liked/<int:pk>/', views.delete_liked, name = "delete_liked"),
    path('delete_orderItem/<int:pk>/', views.delete_orderItem, name = "delete_order_item"),
    path('confirm_order/', views.confirm_order, name = "confirm-order"),
    path('select_delivery/', views.select_delivery, name = "select-delivery"),


    
     
]

sazCitysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
import accounts

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('product/', include('products.urls')),
    path('', accounts.views.main_page, name="main-page"),

]
handler404 = 'accounts.views.error_404'

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

products/forms.py
from tkinter import Widget
from .models import *
from django import forms
from django.forms import ModelForm


class Comment_Form(ModelForm):

    class Meta:
        model = Comment
        fields = ['content', 'unknown_user' ]
        labels = {
            "content": ("متن"),
            "unknown_user" : ("کاربر ناشناس")
        }


class Reply_Form(ModelForm):

    class Meta:
        model = Comment
        fields = ['content']
        labels = {
            "content": ("پاسخ شما"),
        }


    

products/views.py
from django.contrib import messages
import json
from django.http import JsonResponse
from django.shortcuts import redirect, render
from .models import *
from django.contrib.auth.decorators import login_required
from .forms import *
from accounts.forms import Profile_form
from django.shortcuts import get_object_or_404
from django.http import  Http404
from django.contrib.auth.decorators import permission_required


def show_products(request, name):#show products of each category
    id_category = get_object_or_404(Category_item,inner_category_name = name).id
    products = Product.objects.filter(category_item = id_category)
    filter = " "

    if 'filter' in request.GET:
        option_id = request.GET['filter']

        if option_id == '1' :
            products = products.order_by('-id')
            filter = "جدید"

        elif option_id == '2':
            products = sorted(products, key= lambda t: int(t.avg_rate()), reverse=True)
            filter = "محبوب"

        elif option_id == '3':
             products = products.order_by('-sold')
             filter = "پر فروش"

        else:
             raise Http404()
   

    context ={
        'products' :products,
        'filter' : filter
        }
    return render (request, 'products/product.html', context)


def result_search(request):
    try:
        query = request.GET.get("search")
        category_items = Category_item.objects.filter(inner_category_name__icontains=query)
        products = Product.objects.filter( product_name__icontains=query) |Product.objects.filter(category_item__in = category_items)
    except:
        raise Http404()

    context = {
        'products' : products ,
    }
     
    return render (request, 'products/product.html', context)


def detail_product(request, pk):
    product = get_object_or_404(Product, id = pk)
    comment_form = Comment_Form()
    comments = product.comment_set.filter(active=True , parent=None).order_by('-id')
    attributes = product.attributes_value_set.all()
    colors = product.color_value_set.filter( quantity__gt = 0)
    reply_form = Reply_Form()

    context={
        'product' : product ,
        'comments' : comments,
        'create_comment' : comment_form,
        'reply_form' : reply_form,
        'attributes' : attributes,
        'colors' : colors
    }
    
    return render(request, 'products/detail_product.html', context)


@login_required(login_url='/')  # return 302
def send_comment(request, pk):
    
    if request.method == "POST":
        comment_form = Comment_Form(request.POST)

        if comment_form.is_valid():
            instance = comment_form.save(commit = False)
            instance.user = request.user
            instance.product = Product.objects.get(id = pk)
            if 'rating' in request.POST:
               instance.rate = request.POST['rating']
            instance.save()

        return redirect('products:detail-product', pk)

    raise Http404()


@login_required(login_url='/')
#@permission_required("products.add_reply", raise_exception=True)# return 403
def send_reply(request,pk):
    if request.method == "POST":
        reply_from = Reply_Form(request.POST)
        parent_id = request.POST['parent_id']
        parent = Comment.objects.get(id = parent_id)
        product = parent.product

        if reply_from.is_valid():
            instance = reply_from.save(commit = False)
            instance.user = request.user
            instance.parent = parent
            instance.product = product
            instance.save()

        return redirect('products:detail-product', pk)

    raise Http404()


@login_required(login_url='/')  
def add_likes(request, pk):

    if request.method == "POST":
        product = Product.objects.get(id = pk)
        user = request.user
        #liked_by_user = user.liked_product_set.values('product')
        liked , created = Liked_product.objects.get_or_create(user=user, product=product)
    
        if created:
            messages.success(request, 'محصول مورد نظر به علاقه مندی ها اضافه شد')

        else:
            messages.warning(request, 'محصول مورد نظر را قبلا لایک کرده اید')

        return redirect('products:detail-product', pk)
    raise Http404()


@login_required(login_url='/')  
def add_order(request):
    if request.method=='POST':
        data = json.loads(request.body)
        productId = data['productId']
        colorValueId = data['colorValueId']
        product = Product.objects.get(id = productId)
        user = request.user
        color_value = Color_value.objects.filter(id=colorValueId, quantity__gt=0)
        
        order, created = Order.objects.get_or_create(user=user, complete=False)

        if product.total_number() > 0 and color_value:

            color = color_value[0].color
            order_item, created = Order_items.objects.get_or_create(order=order, product=product, color=color)
            if created:
                messages.success(request, 'محصول مورد نظر اضافه شد')
            if not created :
                messages.warning(request, 'محصول مورد نظر را قبلا اضافه کرده اید')
        else:
            messages.warning(request, 'محصول مورد نظر موجود نیست')

        return JsonResponse('add_order', safe=False)
    raise Http404()


@login_required(login_url='/')  
def update_order(request):
    if request.method=='POST':
        data = json.loads(request.body)
        orderItemId = data['orderItemId']
        action = data['action']
    
        order_item = Order_items.objects.get(id=orderItemId)
        color = order_item.color
        total_quantity = order_item.product.color_value_set.get(color=color).quantity

        if action=="add":
            remain_quantity = total_quantity - order_item.qunatity
            if remain_quantity > 0:
                order_item.qunatity = (order_item.qunatity + 1)
                order_item.save()

            else:
                messages.warning(request, 'محصول مورد نظر به این تعداد موجود نیست')

        elif action=="remove":
            order_item.qunatity -= 1
            order_item.save()

        if order_item.qunatity == 0 :
            messages.warning(request, 'محصول مورد نظر حذف شد')
            order_item.delete()

        return JsonResponse('update_order', safe=False)
    raise Http404()


@login_required(login_url='/')  
def show_likes(request):
    user = request.user
    likes = user.liked_product_set.all()

    context = {
        'likes' : likes
    }

    return render(request, 'products/userlikes.html', context)


@login_required(login_url='/')  
def show_cart(request):
    order, created = Order.objects.get_or_create(user=request.user, complete=False)
    order_items = order.order_items_set.all()
    deliveries = Delivery.objects.all()
    context ={
        'order_items': order_items,
        'order': order,
        'deliveries' : deliveries
    }
    return render(request, 'products/cart.html', context)


@login_required(login_url='/')  
def delete_liked(request, pk):
    if request.method=='POST':
        selected_item = Liked_product.objects.get(id = pk)
        messages.warning(request, 'محصول مورد نظر حذف شد')
        selected_item.delete()

        return redirect('products:liked-list')
    raise Http404()


@login_required(login_url='/')  
def delete_orderItem(request, pk):
    if request.method=='POST':
        selected_item = Order_items.objects.get(id = pk)
        messages.warning(request, 'محصول مورد نظر حذف شد')
        selected_item.delete()

        return redirect('products:show-cart')

    raise Http404()


def about_us(request):
    return render(request, 'products/about_us.html')


@login_required(login_url='/')  
def confirm_order(request):

    order = get_object_or_404(Order, user=request.user, complete=False)

    if Order_items.objects.filter(order=order).count()>0 and order.delivery:

        if request.method == "POST":
            profile_form = Profile_form(request.POST, instance=request.user.user_info)
        
            if profile_form.is_valid():
                profile_form.save()
                order.complete = True
                order.save()
                order.update_quantity()
                order.calculate_userRate()
                return render(request,'products/showResultOfOrder.html', {'order':order})
            else:
                messages.warning(request, 'اطلاعات وارد شده نامعتبر است!')
                return redirect('products:confirm-order')

        profile_form = Profile_form(instance=request.user.user_info)
        context={
            'order' : order,
            'profile_form' : profile_form
        }

        return render(request, 'products/confirm_order.html', context)

    raise Http404()
    


@login_required(login_url='/')  
def select_delivery(request):
    if request.method=='POST':
        value_select = request.POST['select_delivery_type']
        delivery_instance = Delivery.objects.get(id=value_select)
        order = Order.objects.get(user=request.user, complete=False)
        order.delivery = delivery_instance
        order.save()
    return redirect('products:show-cart')

products/templates/products/about_us.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}

{% block extrahead %}

    <link rel="stylesheet" type="text/css" href="{% static 'products/css/style.css' %}">

{% endblock %}

{% block headers %}
{% endblock headers %}


{% block content %}

<div id="about_us">

    <div class="row">
        <div class="col-2"></div>
        <div class="col-8">
            <div>
                <br>
                <h4>معرفی فروشگاه اینترنتی شهر ساز</h4>
                <br>
            
                فروشگاه اینترنتی شهر ساز یک فروشگاه تخصصی آنلاین و نماینده رسمی بازرگانی سپید موج کیان ( نماینده رسمی برند کرگ ) و تاشار قشم ( نماینده رسمی برند یاماها ) می باشد که به عرضه و فروش ساز و تجهیزات استودیویی می‌پردازد. این سایت متشکل از چندین شرکت و فروشگاه تخصصی فعال در عرضه این نوع محصولات میباشد. فعالیت‌های این فروشگاه بر روی محصولات دیجیتال و آکوستیک اعم از پیانو، کیبورد، گیتار ، افکت، آمپلی فایر، میکسر، تیونر، و سایر تجهیزات مرتبط، ساز های سنتی، ساز های بادی، ساز های کوبه ای، ساز های زهی، تجهیزات اجرای زنده و تجهیزات استودیویی در برند های مختلف از مبتدی تا حرفه ای برای رفع نیاز شما علاقه مندان در نظر گرفته شده است. با استفاده از خدمات این سایت می‌توانید ویژگی‌های هر کدام از محصولات را مشاهده نمایید و به صورت آنلاین یا تلفنی از کارشناسان شهر ساز مشاوره رایگان بگیرید. با توسعه و پیشرفت روز افزون تجارت الکترونیک در سراسر جهان خرید آنلاین در بین مردم از جایگاه ویژه ای برخوردار شده است.شهر ساز مرجع تخصصی فروش ساز و تجهیزات استودیویی در ایران با بیش از سه هزار محصول، این افتخار را دارد تا با عرضه معتبرترین برند های جهان با نازلترین قیمت ها و با فروش اقساطی 24 ماهه با سقف نامحدود برای سراسر ایران بستر مناسبی برای خرید و فروش آلات موسیقی در بین علاقه مندان و هنر جویان عزیز فراهم آورد.
            </div>
            
            <div>
                <h4>چرا از شهر ساز خرید کنیم؟</h4> 
                <br>
                اطمینان از اصالت کالا با بهترین قیمت ممکن، ارائه اطلاعات کارشناسی مرتبط با ساز یا تجهیزات مد نظر شما، بروز ترین و برترین برند های موجود در جهان موسیقی، یک هفته مهلت تست برای تمامی سازها و نمایندگی رسمی برندهای معتبر موسیقی در ایران از جمله مواردی است که شهر ساز برای رضایت مشتری در نظر گرفته است. تمامی آلات موسیقی توسط کارشناسان شهر ساز بررسی و تایید شده تا ساز و تجهیزات مد نظرتان را بدون هیچگونه نگرانی از نقص فنی یا هرگونه مشکل همراه با ارسال رایگان درب منزل در سراسر ایران تحویل بگیرید، همچنین فروشگاه شهر ساز امکان خرید حضوری ( با هماهنگی قبلی ) جهت تست و بازدید انواع ساز و تجهیزات استودیویی را برای شما عزیزان فراهم کرده است.
            </div>
    </div>
        <div class="col-2"></div>
    </div>
    
</div>

{% endblock content %}

products/templates/products/cart.html
{% extends 'base.html' %}
{% load humanize %}
{% load static %}

{% block headers %}
    <link rel="stylesheet" type="text/css" href="{% static 'products/css/style.css' %}">
{% endblock headers %}


{% block content %}

  <div class="messages">
  {% if messages %}
    <ul >
        {% for message in messages %}
        <li>
            <div class="alert alert-{{ message.tags }}" role="alert">{{ message }}</div>
        </li>
        {% endfor %}
    </ul>
  {% endif %}
  </div>
  <div class="cart table-responsive">
    <table class="table">
      <thead>
        <tr>
          <th scope="col"></th>
          <th scope="col">تصویر</th>
          <th scope="col">نام</th>
          <th scope="col"></th>
          <th scope="col">تعداد</th>
          <th scope="col">قیمت</th>
          <th scope="col">رنگ</th>
          <th scope="col">قیمت کل</th>
        </tr>
      </thead>
      <tbody>
        {% for item in order_items %}
           <tr>
              <td  class="align-middle" >     
                <form  action="{% url 'products:delete_order_item' item.id %}" method="POST">
                    {% csrf_token %}
                    <button class="btn text-danger" type="submit" ><span class="fa fa-trash" aria-hidden="true"></span></button>
                </form>
              </td>
              <td class="align-middle">             
                 <a href="{% url 'products:detail-product' item.product.id %}">
                     <img src="{{item.product.pic.url}}" alt="">
                 </a>
              </td>
             <td class="align-middle">{{item.product.product_name}}</td>
             <td class="handle_quantity align-middle"> 
                <div data-item="{{item.id}}" data-action="add" class="update-cart"> <div class="btn btn-outline-danger btn-sm"> <i class="fa fa-angle-up" aria-hidden="true"></i></div> </div>
                <div data-item="{{item.id}}" data-action="remove" class="update-cart"> <div class="btn btn-outline-danger btn-sm"><i class="fa fa-angle-down" aria-hidden="true"></i></div></div>      
             </td>
             <td class="align-middle">{{item.qunatity}}</td>
             {% if item.product.discount %}
                <td class="align-middle" style="color: rgb(246, 20, 20);"><span style="font-weight: bold;">{{item.product.get_discount|intcomma}}</span> ریال</td>
             {% else %}
                <td class="align-middle" style="color: rgb(246, 20, 20);"><span style="font-weight: bold;">{{item.product.price|intcomma}}</span> ریال</td>
             {% endif %}
             <td class="align-middle">{{item.color}}</td>
             <td class="align-middle" style="color: rgb(246, 20, 20);"><span style="font-weight: bold;">{{item.get_total_price|intcomma}}</span> ریال</td>
           </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
  
    {% if order_items %}
      <div class="delivery row">
        <div class="col"></div>

        <div>
          {% if order.is_free_delivery %}
             <h6 style="color:red">«به دلیل داشتن امتیاز بالای 500 هزینه ارسال برای شما رایگان در نظر گرفته می شود»</h6>
          {% endif %}
          <form action="{% url 'products:select-delivery'%}"  method="POST">
            {% csrf_token %}
            <h6 style="font-weight: bold;text-align: center;">نحوه ارسال را انتخاب کنید:</h6>
            <hr>
            <select name='select_delivery_type' onchange='if(this.value != 0) { this.form.submit(); }'>
              <option value='0'>{% if order.delivery %}{{order.delivery}}{% endif %}</option>
              {% for delivery in deliveries%}
                 <option value='{{delivery.id}}'>{{delivery.type}}</option>
              {% endfor %}
            </select>
          </form>
          {% if order.delivery %}
            <div class="choose_delivery">
              <div style="color: brown;"><span >هزینه ارسال : </span><b>{{order.get_delivery_price|intcomma}}</b> ریال</div>
              <div style="color: brown;"><span >هزینه کل : </span><b>{{order.total_price|intcomma}}</b> ریال</div>
            </div>
          {% endif %}
        </div>
        
        <div class="col"></div>
      </div>
        
      <div class="button_wrapper">
          <a  href ="{% url 'products:confirm-order'%}" class="btn btn-danger">تایید و ادامه  </a>
      </div> 
      
    {% endif %}
  
{% endblock content %}


{% block script %}
  <script src="{% static 'products/js/jq.js' %}"></script>
{% endblock %}

products/templates/products/detail_product.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}

{% block extrahead %}

    <link rel="stylesheet" type="text/css" href="{% static 'products/css/style.css' %}">

{% endblock %}

{% block banner %}{% endblock banner%}

{% block content %}

  <div class="messages">
      {% if messages %}
      <ul>
          {% for message in messages %}
          <li>
              <div class="alert alert-{{ message.tags }}" role="alert">{{ message }}</div>
          </li>
          {% endfor %}
      </ul>
    {% endif %}
  </div>
  
  <div class="procuct_cover">

      <nav aria-label="breadcrumb">
        <ul class="breadcrumb">
          <li class="breadcrumb-item active" aria-current="page"><a href="{% url 'products:show-products' product.category_item.inner_category_name %}"> {{product.category_item}}</a></li>
          <li class="breadcrumb-item">{{product.product_name}}</li>  
        </ul>
      </nav>

      <div class="row">

        <div class="col-12 col-md-12 col-lg-7">   
          <img class="product_pic" src="{{product.pic.url}}">
        </div>

        <div class="sell_table col-12 col-md-12 col-lg-5">

            <h3>{{product.product_name}}</h3>
            <ul class="info" type="none">

                <li><span class="fa fa-check text-danger"></span> ضمانت اصالت کالا</li>
                <hr>
                <li><span class="fa fa-star text-danger" ></span> {{product.avg_rate}} امتیاز از دید کاربران</li> 
                <hr>
                {% if product.discount %}
                  <li class="line-through"><span class="fa fa-money text-danger"></span>  {{product.price|intcomma}} ریال </li>
                  <li class=" text-danger"><span class="fa fa-money"></span>  {{product.get_discount|intcomma}} ریال</li>  
                {% else %}
                  <li><span class="fa fa-money text-danger"></span>  {{product.price|intcomma}} ریال</li> 
                {% endif %}
                <hr>
                {% if product.total_number == 0 %}
                  <li> {{product.existance}}</li>
                {% else %}
                    <li> {{product.total_number}}  عدد در انبار  </li>
                {% endif %}
         
            </ul> 

            <div class="choice_color">
                  <div id="colors">
                    {% for color in colors %}
                          {{color.color}} <input type="radio" name="color" value="{{color.id}}" />
                    {% endfor %}
                  </div>
                <div style="display:flex;align-items:center;justify-content:center;"><button data-product="{{product.id}}" data-action="addOrder"  class="btn btn-sm update-cart btn-danger">افزون به سبد خرید</button> </div>
            </div>

            <div style="display:flex;align-items:center;justify-content:center;">
              <form action="{% url 'products:add-likes' product.id %}" method="POST">
                {% csrf_token %}
                <button type="submit" class="btn text-danger border-danger btn-sm" ><span class="fa fa-thumbs-up"></span> افزودن به علاقمندی</button>
              </form>
            </div>

        </div>

      </div>

  </div>

  <div class="procuct_cover">

    <div class="details">

        <ul class="row" type="none">
          <li class="col"><a href="#explain">توضیحات</a></li>
          <li class="col"><a href="#characteristics">مشخصات</a></li>
          <li class="col"><a href="#comments">نظرات</a></li>
        </ul>

        {% autoescape off %}
            <div class="item" id="explain"> {{product.product_description|linebreaks }}</div>
        {% endautoescape %}

        <div class="item" id="characteristics">
          <table class="table  table-striped">
            <tbody>
            {% if attributes %}  
              {% for attribute in attributes %}
                <tr>
                  <td>{{attribute.att}}</td>
                  <td>{{attribute.value}}</td>
                </tr>
              {% endfor %}
            {% endif %}
            </tbody>
          </table>
        </div>

        <div class="item"><h4>دیدگاه خود را بنویسید</h4></div>
        <div class="item" id="comments">

          <form action="{% url 'products:send-comment' product.id %}" method="POST">
            {% csrf_token %}

            <div class="rating">
              <fieldset class="rating">
                <h5>امتیاز دهید : </h5>
                <input type="radio" id="star5" name="rating" value="5" /><label for="star5" >5 stars</label>
                <input type="radio" id="star4" name="rating" value="4" /><label for="star4" >4 stars</label>
                <input type="radio" id="star3" name="rating" value="3" /><label for="star3" >3 stars</label>
                <input type="radio" id="star2" name="rating" value="2" /><label for="star2" >2 stars</label>
                <input type="radio" id="star1" name="rating" value="1" /><label for="star1" >1 star</label>
            </fieldset>
            </div>

              {% for field in create_comment %}
                <div>
                  {{field.errors}}
                  {{field.label}}
                  {{field}}
                </div>  
              {% endfor %}
            <button type="submit" class="btn btn-danger">ارسال نظر</button>
      
          </form>


          <div style="clear:both"><h5> {{comments.count}} دیدگاه</h5></div> 
            {% for comment in comments %}
              <div class="commnt">
                
                  {% if comment.unknown_user %}
                    <p style="float:right;"> کاربر ناشناس </p>
                  {% else %}
                    <p style="float:right;color: brown;">{{comment.user.username}}</p>
                  {% endif %}
                  
                  <p style="float:right;margin-right:11px;font-size: smaller;" data-rate="{{comment.rate}}" class="show_rate">
                    <span class="fa fa-star"></span>
                    <span class="fa fa-star"></span>
                    <span class="fa fa-star"></span>
                    <span class="fa fa-star"></span>
                    <span class="fa fa-star"></span>
                  </p>
    
                  <p style="float: left;font-size: smaller;">{{comment.date.day}}/{{comment.date.month}}/{{comment.date.year}}</p>
                  <p style="clear: both">{{comment.content}}</p>


                  <button class="reply_btn btn btn-sm btn-primary m-1">پاسخ</button>
                  <div class="reply_form">
                    <form method="POST" action="{% url 'products:send-reply' product.id %}">
                      {% csrf_token %}
                      {{reply_form}}
                        <button type="submit" class="btn btn-danger btn-sm" name="parent_id" value="{{comment.id}}">ارسال</button>
                    </form>
                  </div>
                  <br><br>
                  {% if comment.replies.all %}
                    <button class="toggle_reply btn-sm btn"><i class="fa fa-angle-down" aria-hidden="true"></i></button>
                    <div class="reply">
                      <div style="clear:both;margin-bottom:20px;"><h6> {{comment.replies.count}} پاسخ</h6></div>
                      {% for replay in comment.replies.all %}
                          <hr>
                          <p class="info" style="color: brown;">{{ replay.user.username }} | {{replay.date.day}}/{{replay.date.month}}/{{replay.date.year}}</p>
                          <p>{{ replay.content }}</p>
                          <button class="reply_btn btn btn-sm btn-secondary">پاسخ</button>
                          <div class="reply_form">
                            <form method="POST" action="{% url 'products:send-reply' product.id %}">
                              {% csrf_token %}
                              {{reply_form}}
                                <button type="submit" class="btn btn-danger btn-sm" name="parent_id" value="{{replay.id}}">ارسال</button>
                            </form>
                          </div>

                          <br><br>

                          {% if replay.replies.all %}
                            <div class="innerReply">
                              {% for inner_reply in replay.replies.all %}
                                  <p class="info" style="color: brown;">{{ inner_reply.user.username }} | {{inner_reply.date.day}}/{{inner_reply.date.month}}/{{inner_reply.date.year}}</p>
                                  <p>{{ inner_reply.content }}</p>
                                  <hr>
                              {% endfor %}
                            </div>
                          {% endif %}


                      {% endfor %}
                    </div>
                    <br>
                  {% endif %}

              </div>     
          {% endfor %}

        </div>
    
    </div>

  </div>
  
{% endblock content %}
{% block script %}
 
  <script src="{% static 'products/js/jq.js' %}"></script>
{% endblock %}

products/templates/products/showResultOfOrder.html
{% extends 'base.html' %}
{% load static %}


{% block headers %}
{% endblock headers %}

{% block navbar %}
{% endblock navbar %}

{% block content %}

<div style="display:flex;justify-content:center;margin-top:4%">
    <div style="background-color:#4BB543;width:60%;color:rgb(255, 255, 255) ;padding:2%;">
        <h2 style="text-align: center;">سفارش شما با موفقیت ثبت شد</h2>
        <p style="text-align: center;">شماره سفارش شما برای پیگیری : {{order.id}} </p>
    </div>
</div>

<div class="button_wrapper"> <a class="btn btn-success" type="submit" href="{% url 'main-page'%}">بازگشت به صفحه اصلی</a></div> 

{% endblock content %}

{% block footer %}
{% endblock footer %}

products/templates/products/userlikes.html
{% extends 'base.html' %}
{% load humanize %}
{% load static %}


{% block extrahead %}

    <link rel="stylesheet" type="text/css" href="{% static 'products/css/style.css' %}">

{% endblock %}


{% block headers %}
{% endblock headers %}


{% block content %}

    <div class="messages" >
        {% if messages %}
        <ul >
            {% for message in messages %}
            <li>
                <div class="alert alert-{{ message.tags }}" role="alert">{{ message }}</div>
            </li>
            {% endfor %}
        </ul>
      {% endif %}
    </div>

    <div class="user-likes">
      <table class="table" >
        <thead>
          <tr>
            <th scope="col">تصویر</th>
            <th scope="col">نام</th>
            <th scope="col">قیمت</th>
            <th scope="col">ویرایش</th>
          </tr>
        </thead>
        <tbody>
          {% for item in likes %}
            <tr>
              <td class="align-middle"> 
                  <a style="display:block" href="{% url 'products:detail-product' item.product.id %}">
                      <img height="60" width="60" src="{{item.product.pic.url}}" alt="">
                  </a>
              </td>
              <td class="align-middle">{{item.product.product_name}}</td>
              <td class="align-middle">{{item.product.price|intcomma}} ریال</td>
              <td class="align-middle row">
                  
                  <form class="col-2" action="{% url 'products:delete_liked' item.id %}" method="POST">
                      {% csrf_token %}
                      <button class="btn text-danger" type="submit" ><span class="fa fa-trash" aria-hidden="true"></span></button>
                  </form>
              </td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
   </div>
{% endblock content %}